version: '3'
services:

  plantuml:
    image: plantuml/plantuml-server
    container_name: plantuml
    environment:
      - ALLOW_PLANTUML_INCLUDE=true
    volumes:
      - ./themes:/include
      - $HOME/.cache/wal/plantuml.puml:/include/plantuml.puml
    ports:
      - 4928:8080
    restart: unless-stopped
